version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak-erp
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/realm-erp.json:/opt/keycloak/data/import/realm-erp.json
    command: >
      start-dev
      --import-realm

  postgres-erp:
    image: postgres:16
    container_name: postgres-erp
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - datos_postgres_erp:/var/lib/postgresql/data
      - ./postgres/inicializacion:/docker-entrypoint-initdb.d

volumes:
  datos_postgres_erp:
