version: "3.9"

services:
  postgres-erp:
    image: postgres:16
    container_name: postgres-erp
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
    volumes:
      - datos_postgres_erp:/var/lib/postgresql/data
      - ./postgres/inicializacion:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d keycloak"]
      interval: 5s
      timeout: 3s
      retries: 20

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak-erp
    depends_on:
      postgres-erp:
        condition: service_healthy
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-erp:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres123

      # opcional, útil cuando estás en local
      KC_HTTP_ENABLED: "true"
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/realm-erp.json:/opt/keycloak/data/import/realm-erp.json
    command: ["start-dev"]

volumes:
  datos_postgres_erp:
